<a href="https://colab.research.google.com/github/beneditomacedo/dl_notebooks/blob/master/Basics_of_Linear_Algebra_for_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section III

## Chapter 4 - Introduction to NumPy Arrays

In [31]:
import numpy as np

In [32]:
# create an array
#
l = [1.0,2.0,3.0]
a = np.array(l)
#
print(a)
print(a.shape)
print(a.dtype)
type(a)

[1. 2. 3.]
(3,)
float64


numpy.ndarray

In [33]:
# creating an empty array. Their content will be random and they need to be initialized before use
# 
a = np.empty([3,3])
#
print(a)
print(a.shape)
print(a.dtype)
type(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)
float64


numpy.ndarray

In [34]:
# creating an zeroed array. 
# 
a = np.zeros([3,3])
#
print(a)
print(a.shape)
print(a.dtype)
type(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
float64


numpy.ndarray

In [35]:
# creating an array with 1s
# 
a = np.ones([3,3])
#
print(a)
print(a.shape)
print(a.dtype)
type(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)
float64


numpy.ndarray

In [36]:
# stack vertically arrays
# 
a1 = np.array([1,2,3])
print(a1)
a2 = np.array([4,5,6])
print(a2)
a3 = np.array([7,8,9])
print(a3)
a = np.vstack((a1,a2,a3))
#
print(a)
print(a.shape)
print(a.dtype)
type(a)

[1 2 3]
[4 5 6]
[7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
int64


numpy.ndarray

In [37]:
# stack horizontally arrays
# 
a1 = np.array([1,2,3])
print(a1)
a2 = np.array([4,5,6])
print(a2)
a3 = np.array([7,8,9])
print(a3)
a = np.hstack((a1,a2,a3))
#
print(a)
print(a.shape)
print(a.dtype)
type(a)

[1 2 3]
[4 5 6]
[7 8 9]
[1 2 3 4 5 6 7 8 9]
(9,)
int64


numpy.ndarray

In [38]:
# creating an array with a specific value in every cell
# 
a = np.full([5,3],16)
#
print(a)
print(a.shape)
print(a.dtype)
type(a)

[[16 16 16]
 [16 16 16]
 [16 16 16]
 [16 16 16]
 [16 16 16]]
(5, 3)
int64


numpy.ndarray

In [39]:
# creating an array with a specific value in every cell
# 
a = np.full([5,3],[1,2,3])
#
print(a)
print(a.shape)
print(a.dtype)
type(a)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
(5, 3)
int64


numpy.ndarray

## Chapter 5 - Index, Slice and Reshape NumPy Arrays

### Array Indexing

In [40]:
data = np.array([11,22,33,44,55])
type(data)

numpy.ndarray

In [41]:
print(data[0])
print(data[4])

11
55


In [42]:
print(data[-1])
print(data[-3])

55
33


In [43]:
data = np.array([
[11, 22],
[33, 44],
[55, 66]])
# index data
print(data[0,0])
print(data[2,0])

11
55


In [44]:
# print the first row
print(data[0,])

[11 22]


### Array Slicing

In [45]:
# define array
data = np.array([11, 22, 33, 44, 55])
print(data[:])

[11 22 33 44 55]


In [46]:
print(data[0:1])

[11]


In [47]:
# negative slicing
print(data[-2:])

[44 55]


In [48]:
# define array
data = np.array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])

In [49]:
# remove last column
print(data[:,:-1])

[[11 22]
 [44 55]
 [77 88]]


In [50]:
# select only the last column
print(data[:,-1])

[33 66 99]


In [51]:
# select the second row
data[1:2,:]

array([[44, 55, 66]])

In [52]:
# select the second column
data[:,1:2]

array([[22],
       [55],
       [88]])

In [53]:
# It is common to split a dataset into train and test sets
#
# train = data[:split, :]
# test = data[split:, :]
data = np.array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
split = 2
train,test = data[:split,:],data[split:,:]
print(train)
print('-------------')
print(test)

[[11 22 33]
 [44 55 66]]
-------------
[[77 88 99]]


In [54]:
### Array Reshaping

In [55]:
# define array
data = np.array([11, 22, 33, 44, 55])
print(data.shape)

(5,)


In [56]:
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = np.array(data)
print(data.shape)

(3, 2)


### Reshaping 1D to 2D Array

In [57]:
# define array
data = np.array([11, 22, 33, 44, 55])
print(data)
print(data.shape)
print('-------------')
# reshape
data = data.reshape((data.shape[0], 1))
print(data)
print(data.shape)

[11 22 33 44 55]
(5,)
-------------
[[11]
 [22]
 [33]
 [44]
 [55]]
(5, 1)


In [58]:
data = [[12, 23],[34, 45],[56, 67]]
# array of data
data = np.array(data)
print(data)
print(data.shape)

[[12 23]
 [34 45]
 [56 67]]
(3, 2)


In [59]:
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data)
print(data.shape)

[[[12]
  [23]]

 [[34]
  [45]]

 [[56]
  [67]]]
(3, 2, 1)


### Importing csv data

In [60]:
data = np.genfromtxt('iris_data',delimiter=',')
type(data)

numpy.ndarray

In [61]:
print(data.shape)
data[1:10]

(150, 5)


array([[4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan],
       [5.4, 3.9, 1.7, 0.4, nan],
       [4.6, 3.4, 1.4, 0.3, nan],
       [5. , 3.4, 1.5, 0.2, nan],
       [4.4, 2.9, 1.4, 0.2, nan],
       [4.9, 3.1, 1.5, 0.1, nan]])

In [62]:
# how to load a file with mixed data type. On case below, the last column is "string".
#
data = np.genfromtxt('iris_data',delimiter=',',dtype=None,encoding=None)
type(data)

numpy.ndarray

In [63]:
print(data.shape)
data[1:10]

(150,)


array([(4.9, 3. , 1.4, 0.2, 'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, 'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, 'Iris-setosa'),
       (5. , 3.6, 1.4, 0.2, 'Iris-setosa'),
       (5.4, 3.9, 1.7, 0.4, 'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, 'Iris-setosa'),
       (5. , 3.4, 1.5, 0.2, 'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, 'Iris-setosa')],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', '<U15')])

In [66]:
# removing the last column of a structured array
l = []
for i in range(0,len(data)):
   l.append(list(tuple(data[i])[:-1]))
b = np.array(l)
print(b.shape)
print(b[1:10])

(150, 4)
[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


Chapter 6 - Broadcasting

### Scalar and One Dimension Array

In [67]:
# define array
a = np.array([1, 2, 3])
print(a)
# define scalar
b = 2
print(b)
# broadcast
c = a + b
print(c)

[1 2 3]
2
[3 4 5]


### Scalar and Two Dimension Array

In [69]:
# define array
A = np.array([
[1, 2, 3],
[1, 2, 3]])
print(A)
# define scalar
b = 2
print(b)
# broadcast
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
2
[[3 4 5]
 [3 4 5]]


### One and Two Dimension Array

In [74]:
# define two-dimensional array
A = np.array([
[1, 2, 3],
[1, 2, 3]])
print(A)
print('-------------')
# define one-dimensional array
b = np.array([10, 20, 30])
print(b)
print('-------------')
# broadcast
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
-------------
[10 20 30]
-------------
[[11 22 33]
 [11 22 33]]
